name: Release Derper Docker Image

on:
  push:
    tags:
      - v**

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Release Cli
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "Mmx233/GoReleaseCli"
          latest: true
          fileName: 'release_linux_amd64.tar.gz'
          extract: true
          out-file-path: './build/'

      - name: Build Binary
        run: ./build/release ./cmd/derper -c tar.gz --extra-arches --output build/output --perm 777

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/output/*.tar.gz

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mmx233/derper

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.derper
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/386
