name: Sync Fork

on:
  schedule:
    - cron: '0 12 */7 * *'
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: tailscale
          base: main
          head: main
          token: ${{ secrets.PERSONAL_TOKEN }}